### ISSUE TITLE
New contact form, infinite loading

### ISSUE THREAD

**Issue by dlangham** [CakeWP/cf7-blocks#11]
When creating new form (Contact > Add New), the spinning mountain spins forever.

Would love to use this plugin. <3

Current WP version 6.3.1

![image](https://github.com/CakeWP/cf7-blocks/assets/5368353/65420a27-ecf1-4fa8-b437-3ecea7722a7f)

**Comment by marcinkrzeminski** [comment]
Hey, I can confirm, have the same issue. There are some React related errors in the console.

**Comment by Skrapion** [comment]
Same here. Been using this plugin successfully for most of the year, and now I can't create any new forms or edit any of my old forms. Must be related to a Wordpress or CF7 update.

**Comment by Skrapion** [comment]
It doesn't seem to be related to any CF7 or CF7 Blocks versions. It's not related to Wordpress 6.3.2, but I don't have any backups older than that.

Here's the errors in the log

```
gutenberg-block.min.js:1 Uncaught ReferenceError: n2_ is not defined
    at gutenberg-block.min.js:1:797
    at gutenberg-block.min.js:1:3393
(anonymous) @ gutenberg-block.min.js:1
(anonymous) @ gutenberg-block.min.js:1
data.min.js?ver=1504e29349b8a9d1ae51:2 Store "core/interface" is already registered.
i @ data.min.js?ver=1504e29349b8a9d1ae51:2
register @ data.min.js?ver=1504e29349b8a9d1ae51:2
(anonymous) @ data.min.js?ver=1504e29349b8a9d1ae51:2
508 @ gutenberg.js?ver=2b08a4c8cdbf1b066520:1
r @ gutenberg.js?ver=2b08a4c8cdbf1b066520:42
(anonymous) @ gutenberg.js?ver=2b08a4c8cdbf1b066520:42
r.O @ gutenberg.js?ver=2b08a4c8cdbf1b066520:42
(anonymous) @ gutenberg.js?ver=2b08a4c8cdbf1b066520:42
(anonymous) @ gutenberg.js?ver=2b08a4c8cdbf1b066520:42
cf7-blocks-integrate.js?ver=080408f486f493f8b1e7:1 Uncaught TypeError: Cannot set properties of undefined (setting 'insert')
    at cf7-blocks-integrate.js?ver=080408f486f493f8b1e7:1:513
(anonymous) @ cf7-blocks-integrate.js?ver=080408f486f493f8b1e7:1
load (async)
(anonymous) @ cf7-blocks-integrate.js?ver=080408f486f493f8b1e7:1
deprecated.min.js?ver=73ad3591e7bc95f4777a:2 select( 'core/interface' ).isFeatureActive( scope, featureName ) is deprecated since version 6.0. Please use select( 'core/preferences' ).get( scope, featureName ) instead.
i @ deprecated.min.js?ver=73ad3591e7bc95f4777a:2
(anonymous) @ gutenberg.js?ver=2b08a4c8cdbf1b066520:42
t @ data.min.js?ver=1504e29349b8a9d1ae51:2
r @ data.min.js?ver=1504e29349b8a9d1ae51:2
(anonymous) @ gutenberg.js?ver=2b08a4c8cdbf1b066520:42
(anonymous) @ data.min.js?ver=1504e29349b8a9d1ae51:9
(anonymous) @ data.min.js?ver=1504e29349b8a9d1ae51:9
__unstableMarkListeningStores @ data.min.js?ver=1504e29349b8a9d1ae51:2
(anonymous) @ data.min.js?ver=1504e29349b8a9d1ae51:2
l @ data.min.js?ver=1504e29349b8a9d1ae51:9
(anonymous) @ data.min.js?ver=1504e29349b8a9d1ae51:9
Xe @ data.min.js?ver=1504e29349b8a9d1ae51:9
ze @ data.min.js?ver=1504e29349b8a9d1ae51:9
(anonymous) @ data.min.js?ver=1504e29349b8a9d1ae51:9
wt @ react-dom.min.js?ver=18.2.0:10
js @ react-dom.min.js?ver=18.2.0:10
wl @ react-dom.min.js?ver=18.2.0:10
bl @ react-dom.min.js?ver=18.2.0:10
yl @ react-dom.min.js?ver=18.2.0:10
fl @ react-dom.min.js?ver=18.2.0:10
Nn @ react-dom.min.js?ver=18.2.0:10
El @ react-dom.min.js?ver=18.2.0:10
(anonymous) @ react-dom.min.js?ver=18.2.0:10
v @ react.min.js?ver=18.2.0:10
ce @ react.min.js?ver=18.2.0:10
react-dom.min.js?ver=18.2.0:10 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Dl (react-dom.min.js?ver=18.2.0:10:96134)
    at p (react-dom.min.js?ver=18.2.0:10:42708)
    at g (react-dom.min.js?ver=18.2.0:10:44071)
    at e (react-dom.min.js?ver=18.2.0:10:46135)
    at fr (react-dom.min.js?ver=18.2.0:10:54784)
    at js (react-dom.min.js?ver=18.2.0:10:122397)
    at wl (react-dom.min.js?ver=18.2.0:10:88659)
    at bl (react-dom.min.js?ver=18.2.0:10:88587)
    at yl (react-dom.min.js?ver=18.2.0:10:88450)
    at fl (react-dom.min.js?ver=18.2.0:10:85607)
ar @ react-dom.min.js?ver=18.2.0:10
a.componentDidCatch.t.callback @ react-dom.min.js?ver=18.2.0:10
tt @ react-dom.min.js?ver=18.2.0:10
Jr @ react-dom.min.js?ver=18.2.0:10
Zr @ react-dom.min.js?ver=18.2.0:10
Gr @ react-dom.min.js?ver=18.2.0:10
(anonymous) @ react-dom.min.js?ver=18.2.0:10
xl @ react-dom.min.js?ver=18.2.0:10
fl @ react-dom.min.js?ver=18.2.0:10
Nn @ react-dom.min.js?ver=18.2.0:10
El @ react-dom.min.js?ver=18.2.0:10
(anonymous) @ react-dom.min.js?ver=18.2.0:10
v @ react.min.js?ver=18.2.0:10
ce @ react.min.js?ver=18.2.0:10
```

**Comment by fardeenxyz** [comment]
2024 and here I am, same issue. Had to uninstall the plugin.

**Comment by Skrapion** [comment]
WordPress is now giving an unmaintained warning and the author says this plug-in was just an experiment: https://wordpress.org/support/topic/great-promise-but-abandoned/

A shame, but one of the old update notes for CF7 said it was laying the ground work to support the block editor, so maybe something like this will end up in the core plug-in at some point.

**Comment by Skrapion** [comment]
Here it is: https://contactform7.com/2022/12/10/contact-form-7-57/

Takayuki was planning to get a block editor-based contact form editor released in 2023. Obviously that didn't happen, but [he was still working on the experimental branch last August](https://github.com/rocklobster-in/contact-form-7/tree/experimental/block-based-cf-editor). Maybe a 6.0 reveal?
